---
title: "Insect Group Project Indiv"
author: "Andrei Graham"
date: "2026-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## R Markdown
##Load the Libraries
```{r}
library(tidyverse)
library(janitor)
library(naniar)
library(ggmap)
library(leaflet)
library(sf)
```
##Load in Data
```{r}
insects_ag <- read_csv("data/insects_main.csv")
```

```{r}
#check data structure
glimpse(insects_ag)
```

```{r}
#map
insects_ag %>%
  filter(biomass != "NA")%>%
  select(lat, long) %>% 
  summary()
```

```{r}
register_stadiamaps("824e1e2a-26b0-4511-874e-b93a502f5dce", write = FALSE)
```

```{r}
lat<- c(46.12, 48.76)
long<- c(10.59, 13.41)
bbox<- make_bbox(long, lat, f=0.05)
```

```{r}
#map of where the data came from (hopefully)
map1<- get_stadiamap(bbox, maptype = "stamen_terrain", zoom = 7)
```

```{r}
ggmap(map1)+
  geom_point(data=insects_ag %>%
               filter(long != "NA" & lat != "NA" & biomass!="NA"), aes(long, lat), size=0.8)+
  labs(x="Longitude", y="Latitude", title="Sites Where Biomass was Found")
```

```{r}
#average humidity and biomass
insects_ag%>%
  filter(biomass != "NA" & avg_humidity != "NA")%>%
  group_by(avg_humidity)%>%
  summarise(total_biomass=sum(biomass), n=n())%>%
  select(avg_humidity, total_biomass, n)%>%
  arrange(desc(n))
```

```{r}
#plot average humidity and biomass
insects_ag%>%
  filter(biomass != "NA" & avg_humidity != "NA")%>%
  group_by(avg_humidity)%>%
  summarise(total_biomass=sum(biomass))%>%
  ggplot(aes(x = avg_humidity, y = total_biomass))+
  geom_point(na.rm=TRUE)+
  geom_smooth(method=lm, se=F, na.rm=T)+
  labs(x = "Average Humidity",
       y = "Total Biomass",
       title = "Average Humidity vs Total Biomass")+
  theme_linedraw()

#no strong trend found
```

```{r}
#average temperature and biomass
insects_ag%>%
  filter(biomass != "NA" & avg_temp != "NA")%>%
  group_by(avg_temp)%>%
  summarise(total_biomass=sum(biomass), n=n())%>%
  select(avg_temp, total_biomass, n)%>%
  arrange(desc(n))
```

```{r}
#plot average temperature and biomass
insects_ag%>%
  filter(biomass != "NA" & avg_temp != "NA")%>%
  group_by(avg_temp)%>%
  summarise(total_biomass=sum(biomass))%>%
  ggplot(aes(x = avg_temp, y = total_biomass))+
  geom_point(na.rm=TRUE)+
  geom_smooth(method=lm, se=F, na.rm=T)+
  labs(x = "Average Temperature",
       y = "Total Biomass",
        title = "Average Temp vs Total Biomass")+
  theme_linedraw()

#no strong trend found
```

```{r}
#longterm mean annual precipitation and biomass
insects_ag%>%
  filter(lt_mean_annual_precip != "NA" & biomass != "NA")%>%
  group_by(lt_mean_annual_precip)%>%
  summarise(total_biomass=sum(biomass), n=n())%>%
  select(lt_mean_annual_precip, total_biomass, n)%>%
  arrange(desc(n))
```

```{r}
#plot longterm mean annual precipitation and biomass
insects_ag%>%
  filter(lt_mean_annual_precip != "NA" & biomass != "NA")%>%
  group_by(lt_mean_annual_precip)%>%
  summarise(total_biomass=sum(biomass))%>%
  ggplot(aes(x = lt_mean_annual_precip, y = total_biomass))+
  geom_point(na.rm=TRUE)+
  geom_smooth(method=lm, se=F, na.rm=T)+
  labs(x = "Longterm Mean Annual Precipitation",
       y = "Total Biomass",
        title = "Longterm Mean Annual Precipitation vs Total Biomass")+
  theme_linedraw()

#no strong trend found
```

```{r}
#longterm mean annual average-near surface temperature and biomass
insects_ag%>%
  filter(lt_mean_annual_avg_ns_temp != "NA" & biomass != "NA")%>%
  group_by(lt_mean_annual_avg_ns_temp)%>%
  summarise(total_biomass=sum(biomass), n=n())%>%
  select(lt_mean_annual_avg_ns_temp, total_biomass, n)%>%
  arrange(desc(n))
```

```{r}
#plot longterm mean annual average-near surface temperature and biomass
insects_ag%>%
  filter(lt_mean_annual_avg_ns_temp != "NA" & biomass != "NA")%>%
  group_by(lt_mean_annual_avg_ns_temp)%>%
  summarise(total_biomass=sum(biomass), n=n())%>%
  ggplot(aes(x = lt_mean_annual_avg_ns_temp, y = total_biomass))+
  geom_point(na.rm=TRUE)+
  geom_smooth(method=lm, se=F, na.rm=T)+
  labs(x = "Longterm Mean Annual Average-Near Surface Temperature",
       y = "Total Biomass",
        title = "Longterm Mean Annual Average-Near Surface Temperature vs Total Biomass")+
  theme_linedraw()

#no strong trend found
```

