---
title: "clean_data"
author: "Tyler Sousa & Arlette Hall "
date: "2026-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE, warning=FALSE}
library("tidyverse")
library("janitor")
```

```{r}
insects <- read_csv2("data/insect_raw/Data_Uhler_2021_main.csv") %>% clean_names()
```

```{r}
insects %>%
  miss_var_summary
```

##Clean Data - Arlette
```{r}
#clean possible hidden NAs from character variables
insects <- insects %>%
  replace_with_na_all(condition = ~.x %in% c(common_na_strings))
```

```{r}
insects %>%
  miss_var_summary
```

```{r}
insects <- insects %>%
  rename(avg_temp = average_temperature) %>%
#rename average_humidity to avg_humidity
  rename(avg_humidity = average_humidity) %>%
#rename long_term_mean_annual_precipitation to lt_mean_annual_precip
  rename(lt_mean_annual_precip = long_term_mean_annual_precipitation) %>%
#rename long_term_mean_annual_average_near_surface_temperature to lt_mean_annual_avg_ns_temp
  rename(lt_mean_annual_avg_ns_temp = long_term_mean_annual_average_near_surface_temperature)
```

```{r}
#check numeric variables for hidden NAs
insects %>%
  select(-c(plotid,
             quadrant_id,
             landscape_type,
             landscape_type_2,
             plot_type,
             plot_type_2,
             landscape_plot,
             date_start,
             date_end)) %>%
  summary()

#Per insect_README.txt, values of 0 seen here are not NAs.
#No hidden NAs.
```

```{r}
write_csv(insects, "data/insects_main.csv")
```

