---
title: "Project"
author: "Andrei Graham, Arlette Hall, Tyler Sousa"
date: "2026-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load the Libraries
```{r}
library(tidyverse)
library(janitor)
library(naniar)
library(sf)
library(ggmap)
library(paletteer)
```

##Load in Data
```{r}
insects <- read_csv2("data/insect_raw/Data_Uhler_2021_main.csv") %>%
  clean_names()
```

##Check Data Structure
```{r}
insects %>%
  glimpse()
```

##Clean Data - Arlette
```{r}
#clean possible hidden NAs from character variables
insects <- insects %>%
  replace_with_na_all(condition = ~.x %in% c(common_na_strings))
```

```{r}
#check numeric variables for hidden NAs
insects %>%
  select(-c(plotid,
             quadrant_id,
             landscape_type,
             landscape_type_2,
             plot_type,
             plot_type_2,
             landscape_plot,
             date_start,
             date_end)) %>%
  summary()

#Per insect_README.txt, values of 0 seen here are not NAs.
#No hidden NAs.
```

```{r}
#view NA summary
insects %>%
  miss_var_summary
```

```{r}
#rename average_temperature to avg_temp
insects <- insects %>%
  rename(avg_temp = average_temperature) %>%
#rename average_humidity to avg_humidity
  rename(avg_humidity = average_humidity) %>%
#rename long_term_mean_annual_precipitation to lt_mean_annual_precip
  rename(lt_mean_annual_precip = long_term_mean_annual_precipitation) %>%
#rename long_term_mean_annual_average_near_surface_temperature to lt_mean_annual_avg_ns_temp
  rename(lt_mean_annual_avg_ns_temp = long_term_mean_annual_average_near_surface_temperature)
```

```{r}
#translate coordinates from ETRS89/UTM zone 32N to WGS84, EPSG:4326 (longitude, latitude)

#give each sample a unique ID #
insects <- insects %>%
  mutate(sample_id = row_number())
#copy point_x, point_y, and sample_id to new temp table
temp_coord_table <- insects %>%
  select(point_x, point_y, sample_id)
#convert and save coordinates
temp_coord_table <- temp_coord_table %>%
  st_as_sf(coords = c("point_x", "point_y"), crs = 25832) %>%
  st_transform(crs = 4326) %>%
  mutate(lat = st_coordinates(.)[,1], long = st_coordinates(.)[,2] - 30)
#join temp table to insects table using full_join()
insects <- full_join(insects, temp_coord_table, by="sample_id")
```

```{r}
#check structure of new columns
insects %>%
  select(sample_id, long, lat, geometry) %>%
  glimpse()

#All good, nothing left to correct.
#No date splitting in main cleaned data to avoid column clutter (start_month, end_month, etc.)
```

```{r}
write_csv(insects, "data/insects_main.csv")
```

##Data Exploration - Andrei
```{r}
#load cleaned data as own variable (to not alter others' work)
insects_ag <- read.csv("data/insects_main.csv")
```


##Data Exploration - Arlette
```{r}
#load cleaned data as own variable (to not alter others' work)
insects_ah <- read.csv("data/insects_main.csv")
```

```{r}
#check data structure
insects_ah %>%
  glimpse()
```

#My Questions: How does the number of red-listed species compare across landscape & plot type?

landscape_type & plot_type:
```{r}
#Variable Definitions:
# RL_Richness = No. of species on red-lists for Bavaria/Germany per plot & time frame.
# Landscape_Type = Landscape category of quadrant (agricultural, semi-natural, or urban).
# Plot_Type = Habitat category of plot (arable field, forest, meadow, natural, or settlement).
# Landscape (Quadrant) > Plot

#check landscape_type vs rl_richness
insects_ah %>%
  group_by(landscape_type) %>%
  select(landscape_type, rl_richness) %>%
  na.omit() %>%
  summarize(total_rl_richness = sum(rl_richness), n = n()) %>%
  arrange(desc(total_rl_richness))

#Sampling is even across landscape types
#Semi-natural >> Urban > Agricultural (pesticides?)
```

```{r}
#check plot_type vs rl_richness
insects_ah %>%
  group_by(plot_type) %>%
  select(plot_type, rl_richness) %>%
  na.omit() %>%
  summarize(total_rl_richness = sum(rl_richness), n = n()) %>%
  arrange(desc(total_rl_richness))

#Sampling uneven across plot types. Forests may have just been more prevalent.
#Arable fields sampling on par with meadow & greater than settlement but have much less redlist species.
#Forest >>> Meadow > Settlement >> Arable Field (pesticides?)
```

```{r}
#cluster column chart of landscape_type vs rl_richness by plot_type
insects_ah %>%
  group_by(landscape_type, plot_type) %>%
  select(landscape_type, plot_type, rl_richness) %>%
  na.omit() %>%
  summarize(total_rl_richness = sum(rl_richness),
            .groups='keep') %>%
  ggplot(mapping=aes(x = reorder(landscape_type, total_rl_richness),
                     y = total_rl_richness,
                     fill = plot_type))+
  geom_col(position = "dodge", color = "black", na.rm=T)+
  coord_flip()+
  labs(x = "Landscape", y = NULL,
       title = "No. of Redlist Species Found by Landscape & Plot",
       fill = "Plot")
```

```{r}
#boxplot of landscape_type vs rl_richness by plot_type
insects_ah %>%
  group_by(landscape_type, plot_type) %>%
  select(landscape_type, plot_type, rl_richness) %>%
  na.omit() %>%
  ggplot(mapping=aes(x = reorder(landscape_type, rl_richness),
                     y = rl_richness,
                     fill = plot_type))+
  geom_boxplot(na.rm = T)+
  labs(x = "Landscape", y = NULL,
       title = "No. of Redlist Species Found by Landscape & Plot",
       fill = "Plot")
```

Build a Map:
```{r}
#register
register_stadiamaps("1ad11010-4c59-42b0-a160-0dab4e61577f", write = FALSE)
```

```{r}
#get mins and maxes for longitude & latitude
insects_ah %>%
  select(c(lat, long, rl_richness)) %>%
  filter(lat != "NA" & long != "NA" & rl_richness != "NA") %>% #omit NAs
  summary()
```

```{r}
#set latitude and longitude ranges
lat <- c(46.12, 48.76)
long <- c(10.59, 13.41)
#make bbox with 3% (f=0.03) buffer
bbox <- make_bbox(long, lat, f=0.03)
```

```{r}
#load map
map <- get_stadiamap(bbox, maptype = "stamen_terrain", zoom = 7)
```

```{r}
#plot map by landscape type
ggmap(map)+
  geom_point(data=insects_ah %>%
               filter(rl_richness > 0),
             aes(long, lat, shape = landscape_type), color="black", size=2, alpha=0.3)+
  labs(x="Longitude", y="Latitude", title="Locations of Redlist Species by Landscape Type")
```

```{r}
#plot map by plot type
ggmap(map)+
  geom_point(data=insects_ah %>%
               filter(rl_richness > 0),
             aes(long, lat, shape = plot_type), color="black", size=2, alpha=0.3)+
  labs(x="Longitude", y="Latitude", title="Locations of Redlist Species by Plot Type")
```

##Data Exploration - Tyler
```{r}
#load cleaned data as own variable (to not alter others' work)
insects_ts <- read.csv("data/insects_main.csv")
```


##Shiny App - Andrei




##Shiny App - Arlette




##Shiny App - Tyler